# Generated by Django 2.0.5 on 2018-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cars", "0002_auto_20180526_1424")]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="brands/"),
        )
    ]
